export const EN_STUDENTS = [
  "Airi",
  "Akane",
  "Akane (Bunny Girl)",
  "Akari",
  "Ako",
  "Arisu",
  "Aru",
  "Aru (New Year)",
  "Asuna",
  "Asuna (Bunny Girl)",
  "Atsuko",
  "Ayane",
  "Ayane (Swimsuit)",
  "Azusa",
  "Azusa (Swimsuit)",
  "Cherino",
  "Cherino (Hot Spring)",
  "Chihiro",
  "Chinatsu",
  "Chinatsu (Hot Spring)",
  "Chise",
  "Chise (Swimsuit)",
  "Eimi",
  "Fubuki",
  "Fuuka",
  "Fuuka (New Year)",
  "Hanae",
  "Hanae (Christmas)",
  "Hanako",
  "Hare",
  "Haruka",
  "Haruna",
  "Haruna (New Year)",
  "Hasumi",
  "Hasumi (Sportswear)",
  "Hatsune Miku",
  "Hibiki",
  "Hibiki (Cheerleader)",
  "Hifumi",
  "Hifumi (Swimsuit)",
  "Himari",
  "Hina",
  "Hina (Swimsuit)",
  "Hinata",
  "Hiyori",
  "Hoshino",
  "Hoshino (Swimsuit)",
  "Iori",
  "Iori (Swimsuit)",
  "Iroha",
  "Izumi",
  "Izumi (Swimsuit)",
  "Izuna",
  "Izuna (Swimsuit)",
  "Junko",
  "Junko (New Year)",
  "Juri",
  "Kaede",
  "Kanna",
  "Karin",
  "Karin (Bunny Girl)",
  "Kayoko",
  "Kazusa",
  "Kirino",
  "Koharu",
  "Kokona",
  "Kotama",
  "Kotori",
  "Koyuki",
  "Maki",
  "Mari",
  "Mari (Sportswear)",
  "Marina",
  "Mashiro",
  "Mashiro (Swimsuit)",
  "Megu",
  "Michiru",
  "Midori",
  "Mika",
  "Mimori",
  "Mine",
  "Misaki",
  "Miyako",
  "Miyu",
  "Moe",
  "Momoi",
  "Mutsuki",
  "Mutsuki (New Year)",
  "Nagisa",
  "Natsu",
  "Neru",
  "Neru (Bunny Girl)",
  "Noa",
  "Nodoka",
  "Nodoka (Hot Spring)",
  "Nonomi",
  "Nonomi (Swimsuit)",
  "Pina",
  "Saki",
  "Sakurako",
  "Saori",
  "Saya",
  "Saya (Casual)",
  "Sena",
  "Serika",
  "Serika (New Year)",
  "Serina",
  "Serina (Christmas)",
  "Shigure",
  "Shimiko",
  "Shiroko",
  "Shiroko (Riding)",
  "Shizuko",
  "Shizuko (Swimsuit)",
  "Shun",
  "Shun (Kid)",
  "Sumire",
  "Suzumi",
  "Toki",
  "Tomoe",
  "Tsubaki",
  "Tsukuyo",
  "Tsurugi",
  "Tsurugi (Swimsuit)",
  "Ui",
  "Utaha",
  "Utaha (Cheerleader)",
  "Wakamo",
  "Wakamo (Swimsuit)",
  "Yoshimi",
  "Yuuka",
  "Yuuka (Sportswear)",
  "Yuzu",
];
